org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.212

mod_id=relics_addon
mod_name=EX-twins
mod_archive_name=EX-twins
mod_version=1.0.0-beta.1
mod_group_id=dev.hurtify.relicsaddon
mod_authors=Hurtify
mod_description=Expandable reactive shields and typed combat drone hives for Relics 1.21.1-0.12.8.
